package me.vektory79.vulkan.kotlin.flags

import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_BT2020_LINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_BT709_LINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_BT709_NONLINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_DCI_P3_LINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_DOLBYVISION_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_HDR10_HLG_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_HDR10_ST2084_EXT
import org.lwjgl.vulkan.EXTSwapchainColorspace.VK_COLOR_SPACE_PASS_THROUGH_EXT
import org.lwjgl.vulkan.KHRSurface.VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
import java.rmi.UnexpectedException

enum class KVkColorSpaceKHR(val value: Int) {
    SRGB_NONLINEAR(VK_COLOR_SPACE_SRGB_NONLINEAR_KHR),
    DISPLAY_P3_NONLINEAR(VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT),
    EXTENDED_SRGB_LINEAR(VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT),
    DISPLAY_P3_LINEAR(VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT),
    DCI_P3_NONLINEAR(VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT),
    BT709_LINEAR(VK_COLOR_SPACE_BT709_LINEAR_EXT),
    BT709_NONLINEAR(VK_COLOR_SPACE_BT709_NONLINEAR_EXT),
    BT2020_LINEAR(VK_COLOR_SPACE_BT2020_LINEAR_EXT),
    HDR10_ST2084(VK_COLOR_SPACE_HDR10_ST2084_EXT),
    DOLBYVISION(VK_COLOR_SPACE_DOLBYVISION_EXT),
    HDR10_HLG(VK_COLOR_SPACE_HDR10_HLG_EXT),
    ADOBERGB_LINEAR(VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT),
    ADOBERGB_NONLINEAR(VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT),
    PASS_THROUGH(VK_COLOR_SPACE_PASS_THROUGH_EXT),
    EXTENDED_SRGB_NONLINEAR(VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT),
    DCI_P3_LINEAR(VK_COLOR_SPACE_DCI_P3_LINEAR_EXT);

    companion object {
        fun toEnum(value: Int): KVkColorSpaceKHR {
            return when(value) {
                VK_COLOR_SPACE_SRGB_NONLINEAR_KHR -> SRGB_NONLINEAR
                VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT -> DISPLAY_P3_NONLINEAR
                VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT -> EXTENDED_SRGB_LINEAR
                VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT -> DISPLAY_P3_LINEAR
                VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT -> DCI_P3_NONLINEAR
                VK_COLOR_SPACE_BT709_LINEAR_EXT -> BT709_LINEAR
                VK_COLOR_SPACE_BT709_NONLINEAR_EXT -> BT709_NONLINEAR
                VK_COLOR_SPACE_BT2020_LINEAR_EXT -> BT2020_LINEAR
                VK_COLOR_SPACE_HDR10_ST2084_EXT -> HDR10_ST2084
                VK_COLOR_SPACE_DOLBYVISION_EXT -> DOLBYVISION
                VK_COLOR_SPACE_HDR10_HLG_EXT -> HDR10_HLG
                VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT -> ADOBERGB_LINEAR
                VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT -> ADOBERGB_NONLINEAR
                VK_COLOR_SPACE_PASS_THROUGH_EXT -> PASS_THROUGH
                VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT -> EXTENDED_SRGB_NONLINEAR
                VK_COLOR_SPACE_DCI_P3_LINEAR_EXT -> DCI_P3_LINEAR
                else -> throw UnexpectedException("Unexpected color space")
            }
        }
    }
}